language: cpp
dist: bionic
compiler:
    - gcc
    - clang
script:
    - cmake . -DPPRINT_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PWD/prefix
    - cmake --build .
    - cmake --build . --target package_source
    - cmake --build . --target install
    - ctest . --verbose-on-failure
