package:
  name: startle
  version: "1.0.0"

source:
  path: ..

build:
  script: cmake . && make && mkdir -p ${PREFIX}/bin && mv src/startle ${PREFIX}/bin

requirements:
  build:
    - {{ compiler('cxx') }}

about:
  home: https://github.com/raphael-group/startle/
  license: MIT
  summary: "startle: a maximum parsimony model for lineage tracing"
